export const NewsData = [
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout1.jpg",
    title: "Chelsea",
    desc: "How Watkins and lngs have forged a potent partnership",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Get info about the 2022 World Cup group stage draw.",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout1.jpg",
    title: "Chelsea",
    desc: "Get info about the 2022 World Cup group stage draw.",
    tag: "Football",
    time: "1hr ago",
  },

  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
  {
    image: "assets/images/shout.jpg",
    title: "Chelsea",
    desc: "Butler returns to New England",
    tag: "Football",
    time: "1hr ago",
  },
];
